@startuml Architecture
class Pokemon {
    +mainType : PokemonType
    +secondaryType : PokemonType
    +moves : 
}
class PokemonMove {
    +primaryType : PokemonType
}
class PokemonType {}

Pokemon "1" *-- "6" PokemonMove : has
Pokemon "1" *-- "1..2" PokemonType : has
@enduml